# Generated by Django 3.1.3 on 2020-11-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20201122_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='osxdid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='osxsid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
