# Generated by Django 3.1.3 on 2020-11-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20201122_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='osxdid',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='osxsid',
            field=models.IntegerField(default=1),
        ),
    ]
