# Generated by Django 3.1.3 on 2020-11-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_constant'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ready',
            field=models.BooleanField(default=True),
        ),
    ]
